### ISSUE TITLE
how to change googlelogin ux_mode

### ISSUE THREAD

**Issue by Rachael0108** [yobaji/vue3-google-login#20] opened 2023-02-04 09:39 UTC
i want to use googlelogin button in the mobile phone ,but ux_mode is popup
can i change the display mode  with redirect ? please show me an example ,thanks a lot

**Comment by yobaji** [comment] 2023-02-06 09:51
@Rachael0108 can you look into this issue?
https://github.com/yobaji/vue3-google-login/issues/8

**Comment by yobaji** [comment] 2023-02-13 11:22
Looks like this is a duplicate of another [issue](https://github.com/yobaji/vue3-google-login/issues/8), so I am closing this

**Closed by yobaji** 2023-02-13 11:22 UTC
